name: gh-pages test

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Switch to gh-pages
        run: git checkout gh-pages

      - name: Replace string
        run: |
          sed -i "s/.*Hello.*/Hello ${GITHUB_RUN_ID}\/${GITHUB_RUN_NUMBER}/g" index.html

      - name: Push to gh-pages
        run: |
          git config --global user.name "RETZERO"
          git config --global user.email "ticce@naver.com"
          git add .
          git commit -m "${GITHUB_RUN_ID}/${GITHUB_RUN_NUMBER}"
          git push origin gh-pages
